In [2]:
import numpy as np
import pandas as pd
import scipy as sp
import sklearn as sk
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_excel(r"C:\Users\ACER\OneDrive\Desktop\ML Notes and colab Notebooks\EDA\flight_price.xlsx")
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [4]:
df.shape

(10683, 11)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [6]:
df.Total_Stops.unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [7]:
df.Duration.unique()

array(['2h 50m', '7h 25m', '19h', '5h 25m', '4h 45m', '2h 25m', '15h 30m',
       '21h 5m', '25h 30m', '7h 50m', '13h 15m', '2h 35m', '2h 15m',
       '12h 10m', '26h 35m', '4h 30m', '22h 35m', '23h', '20h 35m',
       '5h 10m', '15h 20m', '2h 55m', '13h 20m', '15h 10m', '5h 45m',
       '5h 55m', '13h 25m', '22h', '5h 30m', '10h 25m', '5h 15m',
       '2h 30m', '6h 15m', '11h 55m', '11h 5m', '8h 30m', '22h 5m',
       '2h 45m', '12h', '16h 5m', '19h 55m', '3h 15m', '25h 20m', '3h',
       '16h 15m', '15h 5m', '6h 30m', '25h 5m', '12h 25m', '27h 20m',
       '10h 15m', '10h 30m', '1h 30m', '1h 25m', '26h 30m', '7h 20m',
       '13h 30m', '5h', '19h 5m', '14h 50m', '2h 40m', '22h 10m',
       '9h 35m', '10h', '21h 20m', '18h 45m', '12h 20m', '18h', '9h 15m',
       '17h 30m', '16h 35m', '12h 15m', '7h 30m', '24h', '8h 55m',
       '7h 10m', '14h 30m', '30h 20m', '15h', '12h 45m', '10h 10m',
       '15h 25m', '14h 5m', '20h 15m', '23h 10m', '18h 10m', '16h',
       '2h 20m', '8h', '16h 55m', '3h 10m', '14h', '23h 50m', '21h 40m',
       '21h 15m', '10h 50m', '8h 15m', '8h 35m', '11h 50m', '27h 35m',
       '8h 25m', '20h 55m', '4h 50m', '8h 10m', '24h 25m', '23h 35m',
       '25h 45m', '26h 10m', '28h 50m', '25h 15m', '9h 20m', '9h 10m',
       '3h 5m', '11h 30m', '9h 30m', '17h 35m', '5h 5m', '25h 50m', '20h',
       '13h', '18h 25m', '24h 10m', '4h 55m', '25h 35m', '6h 20m',
       '18h 40m', '19h 25m', '29h 20m', '9h 5m', '10h 45m', '11h 40m',
       '22h 55m', '37h 25m', '25h 40m', '13h 55m', '8h 40m', '23h 30m',
       '12h 35m', '24h 15m', '1h 20m', '11h', '11h 15m', '14h 35m',
       '12h 55m', '9h', '7h 40m', '11h 45m', '24h 55m', '17h 5m',
       '29h 55m', '22h 15m', '14h 40m', '7h 15m', '20h 10m', '20h 45m',
       '27h', '24h 30m', '20h 25m', '5h 35m', '14h 45m', '5h 40m',
       '4h 5m', '15h 55m', '7h 45m', '28h 20m', '4h 20m', '3h 40m',
       '8h 50m', '23h 45m', '24h 45m', '21h 35m', '8h 5m', '6h 25m',
       '15h 50m', '26h 25m', '24h 50m', '26h', '23h 5m', '7h 55m',
       '26h 20m', '23h 15m', '5h 20m', '4h', '9h 45m', '8h 20m',
       '17h 25m', '7h 5m', '34h 5m', '6h 5m', '5h 50m', '7h', '4h 25m',
       '13h 45m', '19h 15m', '22h 30m', '16h 25m', '13h 50m', '27h 5m',
       '28h 10m', '4h 40m', '15h 40m', '4h 35m', '18h 30m', '38h 15m',
       '6h 35m', '12h 30m', '11h 20m', '7h 35m', '29h 35m', '26h 55m',
       '23h 40m', '12h 50m', '9h 50m', '21h 55m', '10h 55m', '21h 10m',
       '20h 40m', '30h', '13h 10m', '8h 45m', '6h 10m', '17h 45m',
       '21h 45m', '3h 55m', '17h 20m', '30h 30m', '21h 25m', '12h 40m',
       '24h 35m', '19h 10m', '22h 40m', '14h 55m', '21h', '6h 45m',
       '28h 40m', '9h 40m', '16h 40m', '16h 20m', '16h 45m', '1h 15m',
       '6h 55m', '11h 25m', '14h 20m', '12h 5m', '24h 5m', '28h 15m',
       '17h 50m', '20h 20m', '28h 5m', '10h 20m', '14h 15m', '35h 15m',
       '35h 35m', '26h 40m', '28h', '14h 25m', '13h 5m', '37h 20m',
       '36h 10m', '25h 55m', '35h 5m', '19h 45m', '27h 55m', '47h',
       '10h 35m', '1h 35m', '16h 10m', '38h 20m', '6h', '16h 50m',
       '14h 10m', '23h 20m', '17h 40m', '11h 35m', '18h 20m', '6h 40m',
       '30h 55m', '24h 40m', '29h 50m', '28h 25m', '17h 15m', '22h 45m',
       '25h 25m', '21h 50m', '33h 15m', '30h 15m', '3h 35m', '27h 40m',
       '30h 25m', '18h 50m', '27h 45m', '15h 15m', '10h 40m', '26h 15m',
       '36h 25m', '26h 50m', '15h 45m', '19h 40m', '22h 25m', '19h 35m',
       '25h', '26h 45m', '38h', '4h 15m', '25h 10m', '18h 15m', '6h 50m',
       '23h 55m', '17h 55m', '23h 25m', '17h 10m', '24h 20m', '28h 30m',
       '27h 10m', '19h 20m', '15h 35m', '9h 25m', '21h 30m', '34h 25m',
       '18h 35m', '29h 40m', '26h 5m', '29h 5m', '27h 25m', '16h 30m',
       '11h 10m', '28h 55m', '29h 10m', '34h', '30h 40m', '30h 45m',
       '32h 55m', '10h 5m', '35h 20m', '32h 5m', '31h 40m', '19h 50m',
       '33h 45m', '30h 10m', '13h 40m', '19h 30m', '31h 30m', '34h 30m',
       '27h 50m', '38h 35m', '42h 5m', '4h 10m', '39h 5m', '3h 50m', '5m',
       '32h 30m', '31h 55m', '33h 20m', '27h 30m', '18h 55m', '9h 55m',
       '41h 20m', '20h 5m', '31h 50m', '42h 45m', '3h 25m', '37h 10m',
       '29h 30m', '32h 20m', '20h 50m', '40h 20m', '13h 35m', '47h 40m'],
      dtype=object)

In [8]:
for col in df.columns:
    x = df[col].unique()
    print(f"{col}= {x}")
    print()

Airline= ['IndiGo' 'Air India' 'Jet Airways' 'SpiceJet' 'Multiple carriers' 'GoAir'
 'Vistara' 'Air Asia' 'Vistara Premium economy' 'Jet Airways Business'
 'Multiple carriers Premium economy' 'Trujet']

Date_of_Journey= ['24/03/2019' '1/05/2019' '9/06/2019' '12/05/2019' '01/03/2019'
 '24/06/2019' '12/03/2019' '27/05/2019' '1/06/2019' '18/04/2019'
 '9/05/2019' '24/04/2019' '3/03/2019' '15/04/2019' '12/06/2019'
 '6/03/2019' '21/03/2019' '3/04/2019' '6/05/2019' '15/05/2019'
 '18/06/2019' '15/06/2019' '6/04/2019' '18/05/2019' '27/06/2019'
 '21/05/2019' '06/03/2019' '3/06/2019' '15/03/2019' '3/05/2019'
 '9/03/2019' '6/06/2019' '24/05/2019' '09/03/2019' '1/04/2019'
 '21/04/2019' '21/06/2019' '27/03/2019' '18/03/2019' '12/04/2019'
 '9/04/2019' '1/03/2019' '03/03/2019' '27/04/2019']

Source= ['Banglore' 'Kolkata' 'Delhi' 'Chennai' 'Mumbai']

Destination= ['New Delhi' 'Banglore' 'Cochin' 'Kolkata' 'Delhi' 'Hyderabad']

Route= ['BLR → DEL' 'CCU → IXR → BBI → BLR' 'DEL → LKO → BOM → COK'
 'CCU → NAG → BLR' 'BLR → NAG → DEL' 'CCU → BLR' 'BLR → BOM → DEL'
 'DEL → BOM → COK' 'DEL → BLR → COK' 'MAA → CCU' 'CCU → BOM → BLR'
 'DEL → AMD → BOM → COK' 'DEL → PNQ → COK' 'DEL → CCU → BOM → COK'
 'BLR → COK → DEL' 'DEL → IDR → BOM → COK' 'DEL → LKO → COK'
 'CCU → GAU → DEL → BLR' 'DEL → NAG → BOM → COK' 'CCU → MAA → BLR'
 'DEL → HYD → COK' 'CCU → HYD → BLR' 'DEL → COK' 'CCU → DEL → BLR'
 'BLR → BOM → AMD → DEL' 'BOM → DEL → HYD' 'DEL → MAA → COK' 'BOM → HYD'
 'DEL → BHO → BOM → COK' 'DEL → JAI → BOM → COK' 'DEL → ATQ → BOM → COK'
 'DEL → JDH → BOM → COK' 'CCU → BBI → BOM → BLR' 'BLR → MAA → DEL'
 'DEL → GOI → BOM → COK' 'DEL → BDQ → BOM → COK' 'CCU → JAI → BOM → BLR'
 'CCU → BBI → BLR' 'BLR → HYD → DEL' 'DEL → TRV → COK'
 'CCU → IXR → DEL → BLR' 'DEL → IXU → BOM → COK' 'CCU → IXB → BLR'
 'BLR → BOM → JDH → DEL' 'DEL → UDR → BOM → COK' 'DEL → HYD → MAA → COK'
 'CCU → BOM → COK → BLR' 'BLR → CCU → DEL' 'CCU → BOM → GOI → BLR'
 'DEL → RPR → NAG → BOM → COK' 'DEL → HYD → BOM → COK'
 'CCU → DEL → AMD → BLR' 'CCU → PNQ → BLR' 'BLR → CCU → GAU → DEL'
 'CCU → DEL → COK → BLR' 'BLR → PNQ → DEL' 'BOM → JDH → DEL → HYD'
 'BLR → BOM → BHO → DEL' 'DEL → AMD → COK' 'BLR → LKO → DEL'
 'CCU → GAU → BLR' 'BOM → GOI → HYD' 'CCU → BOM → AMD → BLR'
 'CCU → BBI → IXR → DEL → BLR' 'DEL → DED → BOM → COK'
 'DEL → MAA → BOM → COK' 'BLR → AMD → DEL' 'BLR → VGA → DEL'
 'CCU → JAI → DEL → BLR' 'CCU → AMD → BLR' 'CCU → VNS → DEL → BLR'
 'BLR → BOM → IDR → DEL' 'BLR → BBI → DEL' 'BLR → GOI → DEL'
 'BOM → AMD → ISK → HYD' 'BOM → DED → DEL → HYD' 'DEL → IXC → BOM → COK'
 'CCU → PAT → BLR' 'BLR → CCU → BBI → DEL' 'CCU → BBI → HYD → BLR'
 'BLR → BOM → NAG → DEL' 'BLR → CCU → BBI → HYD → DEL' 'BLR → GAU → DEL'
 'BOM → BHO → DEL → HYD' 'BOM → JLR → HYD' 'BLR → HYD → VGA → DEL'
 'CCU → KNU → BLR' 'CCU → BOM → PNQ → BLR' 'DEL → BBI → COK'
 'BLR → VGA → HYD → DEL' 'BOM → JDH → JAI → DEL → HYD'
 'DEL → GWL → IDR → BOM → COK' 'CCU → RPR → HYD → BLR' 'CCU → VTZ → BLR'
 'CCU → DEL → VGA → BLR' 'BLR → BOM → IDR → GWL → DEL'
 'CCU → DEL → COK → TRV → BLR' 'BOM → COK → MAA → HYD' 'BOM → NDC → HYD'
 'BLR → BDQ → DEL' 'CCU → BOM → TRV → BLR' 'CCU → BOM → HBX → BLR'
 'BOM → BDQ → DEL → HYD' 'BOM → CCU → HYD' 'BLR → TRV → COK → DEL'
 'BLR → IDR → DEL' 'CCU → IXZ → MAA → BLR' 'CCU → GAU → IMF → DEL → BLR'
 'BOM → GOI → PNQ → HYD' 'BOM → BLR → CCU → BBI → HYD' 'BOM → MAA → HYD'
 'BLR → BOM → UDR → DEL' 'BOM → UDR → DEL → HYD' 'BLR → VGA → VTZ → DEL'
 'BLR → HBX → BOM → BHO → DEL' 'CCU → IXA → BLR' 'BOM → RPR → VTZ → HYD'
 'BLR → HBX → BOM → AMD → DEL' 'BOM → IDR → DEL → HYD' 'BOM → BLR → HYD'
 'BLR → STV → DEL' 'CCU → IXB → DEL → BLR' 'BOM → JAI → DEL → HYD'
 'BOM → VNS → DEL → HYD' 'BLR → HBX → BOM → NAG → DEL' nan
 'BLR → BOM → IXC → DEL' 'BLR → CCU → BBI → HYD → VGA → DEL'
 'BOM → BBI → HYD']

Dep_Time= ['22:20' '05:50' '09:25' '18:05' '16:50' '09:00' '18:55' '08:00' '08:55'
 '11:25' '09:45' '20:20' '11:40' '21:10' '17:15' '16:40' '08:45' '14:00'
 '20:15' '16:00' '14:10' '22:00' '04:00' '21:25' '21:50' '07:00' '07:05'
 '09:50' '14:35' '10:35' '15:05' '14:15' '06:45' '20:55' '11:10' '05:45'
 '19:00' '23:05' '11:00' '09:35' '21:15' '23:55' '19:45' '08:50' '15:40'
 '06:05' '15:00' '13:55' '05:55' '13:20' '05:05' '06:25' '17:30' '08:20'
 '19:55' '06:30' '14:05' '02:00' '09:40' '08:25' '20:25' '13:15' '02:15'
 '16:55' '20:45' '05:15' '19:50' '20:00' '06:10' '19:30' '04:45' '12:55'
 '18:15' '17:20' '15:25' '23:00' '12:00' '14:45' '11:50' '11:30' '14:40'
 '19:10' '06:00' '23:30' '07:35' '13:05' '12:30' '15:10' '12:50' '18:25'
 '16:30' '00:40' '06:50' '13:00' '19:15' '01:30' '17:00' '10:00' '19:35'
 '15:30' '12:10' '16:10' '20:35' '22:25' '21:05' '05:35' '05:10' '06:40'
 '15:15' '00:30' '08:30' '07:10' '05:30' '14:25' '05:25' '10:20' '17:45'
 '13:10' '22:10' '04:55' '17:50' '21:20' '06:20' '15:55' '20:30' '17:25'
 '09:30' '07:30' '02:35' '10:55' '17:10' '09:10' '18:45' '15:20' '22:50'
 '14:55' '14:20' '13:25' '22:15' '11:05' '16:15' '20:10' '06:55' '19:05'
 '07:55' '07:45' '10:10' '08:15' '11:35' '21:00' '17:55' '16:45' '18:20'
 '03:50' '08:35' '19:20' '20:05' '17:40' '04:40' '17:35' '09:55' '05:00'
 '18:00' '02:55' '20:40' '22:55' '22:40' '21:30' '08:10' '17:05' '07:25'
 '15:45' '09:15' '15:50' '11:45' '22:05' '18:35' '00:25' '19:40' '20:50'
 '22:45' '10:30' '23:25' '11:55' '10:45' '11:15' '12:20' '14:30' '07:15'
 '01:35' '18:40' '09:20' '21:55' '13:50' '01:40' '00:20' '04:15' '13:45'
 '18:30' '06:15' '02:05' '12:15' '13:30' '06:35' '10:05' '08:40' '03:05'
 '21:35' '16:35' '02:30' '16:25' '05:40' '15:35' '13:40' '07:20' '04:50'
 '12:45' '10:25' '12:05' '11:20' '21:40' '03:00']

Arrival_Time= ['01:10 22 Mar' '13:15' '04:25 10 Jun' ... '06:50 10 Mar' '00:05 19 Mar'
 '21:20 13 Mar']

Duration= ['2h 50m' '7h 25m' '19h' '5h 25m' '4h 45m' '2h 25m' '15h 30m' '21h 5m'
 '25h 30m' '7h 50m' '13h 15m' '2h 35m' '2h 15m' '12h 10m' '26h 35m'
 '4h 30m' '22h 35m' '23h' '20h 35m' '5h 10m' '15h 20m' '2h 55m' '13h 20m'
 '15h 10m' '5h 45m' '5h 55m' '13h 25m' '22h' '5h 30m' '10h 25m' '5h 15m'
 '2h 30m' '6h 15m' '11h 55m' '11h 5m' '8h 30m' '22h 5m' '2h 45m' '12h'
 '16h 5m' '19h 55m' '3h 15m' '25h 20m' '3h' '16h 15m' '15h 5m' '6h 30m'
 '25h 5m' '12h 25m' '27h 20m' '10h 15m' '10h 30m' '1h 30m' '1h 25m'
 '26h 30m' '7h 20m' '13h 30m' '5h' '19h 5m' '14h 50m' '2h 40m' '22h 10m'
 '9h 35m' '10h' '21h 20m' '18h 45m' '12h 20m' '18h' '9h 15m' '17h 30m'
 '16h 35m' '12h 15m' '7h 30m' '24h' '8h 55m' '7h 10m' '14h 30m' '30h 20m'
 '15h' '12h 45m' '10h 10m' '15h 25m' '14h 5m' '20h 15m' '23h 10m'
 '18h 10m' '16h' '2h 20m' '8h' '16h 55m' '3h 10m' '14h' '23h 50m'
 '21h 40m' '21h 15m' '10h 50m' '8h 15m' '8h 35m' '11h 50m' '27h 35m'
 '8h 25m' '20h 55m' '4h 50m' '8h 10m' '24h 25m' '23h 35m' '25h 45m'
 '26h 10m' '28h 50m' '25h 15m' '9h 20m' '9h 10m' '3h 5m' '11h 30m'
 '9h 30m' '17h 35m' '5h 5m' '25h 50m' '20h' '13h' '18h 25m' '24h 10m'
 '4h 55m' '25h 35m' '6h 20m' '18h 40m' '19h 25m' '29h 20m' '9h 5m'
 '10h 45m' '11h 40m' '22h 55m' '37h 25m' '25h 40m' '13h 55m' '8h 40m'
 '23h 30m' '12h 35m' '24h 15m' '1h 20m' '11h' '11h 15m' '14h 35m'
 '12h 55m' '9h' '7h 40m' '11h 45m' '24h 55m' '17h 5m' '29h 55m' '22h 15m'
 '14h 40m' '7h 15m' '20h 10m' '20h 45m' '27h' '24h 30m' '20h 25m' '5h 35m'
 '14h 45m' '5h 40m' '4h 5m' '15h 55m' '7h 45m' '28h 20m' '4h 20m' '3h 40m'
 '8h 50m' '23h 45m' '24h 45m' '21h 35m' '8h 5m' '6h 25m' '15h 50m'
 '26h 25m' '24h 50m' '26h' '23h 5m' '7h 55m' '26h 20m' '23h 15m' '5h 20m'
 '4h' '9h 45m' '8h 20m' '17h 25m' '7h 5m' '34h 5m' '6h 5m' '5h 50m' '7h'
 '4h 25m' '13h 45m' '19h 15m' '22h 30m' '16h 25m' '13h 50m' '27h 5m'
 '28h 10m' '4h 40m' '15h 40m' '4h 35m' '18h 30m' '38h 15m' '6h 35m'
 '12h 30m' '11h 20m' '7h 35m' '29h 35m' '26h 55m' '23h 40m' '12h 50m'
 '9h 50m' '21h 55m' '10h 55m' '21h 10m' '20h 40m' '30h' '13h 10m' '8h 45m'
 '6h 10m' '17h 45m' '21h 45m' '3h 55m' '17h 20m' '30h 30m' '21h 25m'
 '12h 40m' '24h 35m' '19h 10m' '22h 40m' '14h 55m' '21h' '6h 45m'
 '28h 40m' '9h 40m' '16h 40m' '16h 20m' '16h 45m' '1h 15m' '6h 55m'
 '11h 25m' '14h 20m' '12h 5m' '24h 5m' '28h 15m' '17h 50m' '20h 20m'
 '28h 5m' '10h 20m' '14h 15m' '35h 15m' '35h 35m' '26h 40m' '28h'
 '14h 25m' '13h 5m' '37h 20m' '36h 10m' '25h 55m' '35h 5m' '19h 45m'
 '27h 55m' '47h' '10h 35m' '1h 35m' '16h 10m' '38h 20m' '6h' '16h 50m'
 '14h 10m' '23h 20m' '17h 40m' '11h 35m' '18h 20m' '6h 40m' '30h 55m'
 '24h 40m' '29h 50m' '28h 25m' '17h 15m' '22h 45m' '25h 25m' '21h 50m'
 '33h 15m' '30h 15m' '3h 35m' '27h 40m' '30h 25m' '18h 50m' '27h 45m'
 '15h 15m' '10h 40m' '26h 15m' '36h 25m' '26h 50m' '15h 45m' '19h 40m'
 '22h 25m' '19h 35m' '25h' '26h 45m' '38h' '4h 15m' '25h 10m' '18h 15m'
 '6h 50m' '23h 55m' '17h 55m' '23h 25m' '17h 10m' '24h 20m' '28h 30m'
 '27h 10m' '19h 20m' '15h 35m' '9h 25m' '21h 30m' '34h 25m' '18h 35m'
 '29h 40m' '26h 5m' '29h 5m' '27h 25m' '16h 30m' '11h 10m' '28h 55m'
 '29h 10m' '34h' '30h 40m' '30h 45m' '32h 55m' '10h 5m' '35h 20m' '32h 5m'
 '31h 40m' '19h 50m' '33h 45m' '30h 10m' '13h 40m' '19h 30m' '31h 30m'
 '34h 30m' '27h 50m' '38h 35m' '42h 5m' '4h 10m' '39h 5m' '3h 50m' '5m'
 '32h 30m' '31h 55m' '33h 20m' '27h 30m' '18h 55m' '9h 55m' '41h 20m'
 '20h 5m' '31h 50m' '42h 45m' '3h 25m' '37h 10m' '29h 30m' '32h 20m'
 '20h 50m' '40h 20m' '13h 35m' '47h 40m']

Total_Stops= ['non-stop' '2 stops' '1 stop' '3 stops' nan '4 stops']

Additional_Info= ['No info' 'In-flight meal not included' 'No check-in baggage included'
 '1 Short layover' 'No Info' '1 Long layover' 'Change airports'
 'Business class' 'Red-eye flight' '2 Long layover']

Price= [ 3897  7662 13882 ...  9790 12352 12648]

In [9]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [10]:
df.dropna(inplace= True)

In [11]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
dtype: int64

In [12]:
df.duplicated(keep = 'first').sum()

np.int64(220)

In [13]:
df.Date_of_Journey

0        24/03/2019
1         1/05/2019
2         9/06/2019
3        12/05/2019
4        01/03/2019
            ...
10678     9/04/2019
10679    27/04/2019
10680    27/04/2019
10681    01/03/2019
10682     9/05/2019
Name: Date_of_Journey, Length: 10682, dtype: object

In [14]:
df['Date_of_Journey'].str.split('/')

0        [24, 03, 2019]
1         [1, 05, 2019]
2         [9, 06, 2019]
3        [12, 05, 2019]
4        [01, 03, 2019]
              ...
10678     [9, 04, 2019]
10679    [27, 04, 2019]
10680    [27, 04, 2019]
10681    [01, 03, 2019]
10682     [9, 05, 2019]
Name: Date_of_Journey, Length: 10682, dtype: object

In [15]:
df['Day'] = df['Date_of_Journey'].str.split('/').str[0]
df['Month'] = df['Date_of_Journey'].str.split('/').str[1]
df['Year'] = df['Date_of_Journey'].str.split('/').str[2]

In [16]:
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Day,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,03,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,05,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,06,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,05,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,01,03,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,9,04,2019
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,27,04,2019
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,27,04,2019
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,01,03,2019
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,9,05,2019

In [17]:
df['Day'] = df['Day'].astype(int)
df['Month'] = df['Month'].astype(int)
df['Year'] = df['Year'].astype(int)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Date_of_Journey  10682 non-null  object
 2   Source           10682 non-null  object
 3   Destination      10682 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10682 non-null  object
 6   Arrival_Time     10682 non-null  object
 7   Duration         10682 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10682 non-null  object
 10  Price            10682 non-null  int64
 11  Day              10682 non-null  int64
 12  Month            10682 non-null  int64
 13  Year             10682 non-null  int64
dtypes: int64(4), object(10)
memory usage: 1.2+ MB

In [19]:
df.drop('Date_of_Journey', axis=1, inplace=True)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10682 non-null  object
 5   Arrival_Time     10682 non-null  object
 6   Duration         10682 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10682 non-null  object
 9   Price            10682 non-null  int64
 10  Day              10682 non-null  int64
 11  Month            10682 non-null  int64
 12  Year             10682 non-null  int64
dtypes: int64(4), object(9)
memory usage: 1.1+ MB

In [21]:
df.Arrival_Time.unique()

array(['01:10 22 Mar', '13:15', '04:25 10 Jun', ..., '06:50 10 Mar',
       '00:05 19 Mar', '21:20 13 Mar'], dtype=object)

In [22]:
df.Arrival_Time = df['Arrival_Time'].str.split(' ').str[0]
df["Arriva_Hour"] = df['Arrival_Time'].str.split(':').str[0]
df["Arriva_Minute"] = df['Arrival_Time'].str.split(':').str[1]

In [23]:
df.drop('Arrival_Time',axis = 1, inplace = True)

In [24]:
df

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Day,Month,Year,Arriva_Hour,Arriva_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897,24,3,2019,01,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,19h,2 stops,No info,13882,9,6,2019,04,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,5h 25m,1 stop,No info,6218,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,4h 45m,1 stop,No info,13302,1,3,2019,21,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,19:55,2h 30m,non-stop,No info,4107,9,4,2019,22,25
10679,Air India,Kolkata,Banglore,CCU → BLR,20:45,2h 35m,non-stop,No info,4145,27,4,2019,23,20
10680,Jet Airways,Banglore,Delhi,BLR → DEL,08:20,3h,non-stop,No info,7229,27,4,2019,11,20
10681,Vistara,Banglore,New Delhi,BLR → DEL,11:30,2h 40m,non-stop,No info,12648,1,3,2019,14,10
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,8h 20m,2 stops,No info,11753,9,5,2019,19,15

In [25]:
df["Arriva_Hour"]  = df["Arriva_Hour"].astype(int)

In [26]:
df["Arriva_Minute"] = df["Arriva_Minute"].astype(int)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10682 non-null  object
 5   Duration         10682 non-null  object
 6   Total_Stops      10682 non-null  object
 7   Additional_Info  10682 non-null  object
 8   Price            10682 non-null  int64
 9   Day              10682 non-null  int64
 10  Month            10682 non-null  int64
 11  Year             10682 non-null  int64
 12  Arriva_Hour      10682 non-null  int64
 13  Arriva_Minute    10682 non-null  int64
dtypes: int64(6), object(8)
memory usage: 1.2+ MB

In [28]:
df.Dep_Time.unique()

array(['22:20', '05:50', '09:25', '18:05', '16:50', '09:00', '18:55',
       '08:00', '08:55', '11:25', '09:45', '20:20', '11:40', '21:10',
       '17:15', '16:40', '08:45', '14:00', '20:15', '16:00', '14:10',
       '22:00', '04:00', '21:25', '21:50', '07:00', '07:05', '09:50',
       '14:35', '10:35', '15:05', '14:15', '06:45', '20:55', '11:10',
       '05:45', '19:00', '23:05', '11:00', '09:35', '21:15', '23:55',
       '19:45', '08:50', '15:40', '06:05', '15:00', '13:55', '05:55',
       '13:20', '05:05', '06:25', '17:30', '08:20', '19:55', '06:30',
       '14:05', '02:00', '09:40', '08:25', '20:25', '13:15', '02:15',
       '16:55', '20:45', '05:15', '19:50', '20:00', '06:10', '19:30',
       '04:45', '12:55', '18:15', '17:20', '15:25', '23:00', '12:00',
       '14:45', '11:50', '11:30', '14:40', '19:10', '06:00', '23:30',
       '07:35', '13:05', '12:30', '15:10', '12:50', '18:25', '16:30',
       '00:40', '06:50', '13:00', '19:15', '01:30', '17:00', '10:00',
       '19:35', '15:30', '12:10', '16:10', '20:35', '22:25', '21:05',
       '05:35', '05:10', '06:40', '15:15', '00:30', '08:30', '07:10',
       '05:30', '14:25', '05:25', '10:20', '17:45', '13:10', '22:10',
       '04:55', '17:50', '21:20', '06:20', '15:55', '20:30', '17:25',
       '09:30', '07:30', '02:35', '10:55', '17:10', '09:10', '18:45',
       '15:20', '22:50', '14:55', '14:20', '13:25', '22:15', '11:05',
       '16:15', '20:10', '06:55', '19:05', '07:55', '07:45', '10:10',
       '08:15', '11:35', '21:00', '17:55', '16:45', '18:20', '03:50',
       '08:35', '19:20', '20:05', '17:40', '04:40', '17:35', '09:55',
       '05:00', '18:00', '02:55', '20:40', '22:55', '22:40', '21:30',
       '08:10', '17:05', '07:25', '15:45', '09:15', '15:50', '11:45',
       '22:05', '18:35', '00:25', '19:40', '20:50', '22:45', '10:30',
       '23:25', '11:55', '10:45', '11:15', '12:20', '14:30', '07:15',
       '01:35', '18:40', '09:20', '21:55', '13:50', '01:40', '00:20',
       '04:15', '13:45', '18:30', '06:15', '02:05', '12:15', '13:30',
       '06:35', '10:05', '08:40', '03:05', '21:35', '16:35', '02:30',
       '16:25', '05:40', '15:35', '13:40', '07:20', '04:50', '12:45',
       '10:25', '12:05', '11:20', '21:40', '03:00'], dtype=object)

In [29]:
df['Dep_Hour'] = df['Dep_Time'].str.split(':').str[0]
df['Dep_Minute'] = df['Dep_Time'].str.split(':').str[1]

In [30]:
df.drop('Dep_Time', axis = 1, inplace = True)

In [31]:
df

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Day,Month,Year,Arriva_Hour,Arriva_Minute,Dep_Hour,Dep_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,1,5,2019,13,15,05,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882,9,6,2019,4,25,09,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218,12,5,2019,23,30,18,05
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302,1,3,2019,21,35,16,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,2h 30m,non-stop,No info,4107,9,4,2019,22,25,19,55
10679,Air India,Kolkata,Banglore,CCU → BLR,2h 35m,non-stop,No info,4145,27,4,2019,23,20,20,45
10680,Jet Airways,Banglore,Delhi,BLR → DEL,3h,non-stop,No info,7229,27,4,2019,11,20,08,20
10681,Vistara,Banglore,New Delhi,BLR → DEL,2h 40m,non-stop,No info,12648,1,3,2019,14,10,11,30
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,8h 20m,2 stops,No info,11753,9,5,2019,19,15,10,55

In [32]:
df.Total_Stops.unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', '4 stops'],
      dtype=object)

In [33]:
df.Total_Stops = df.Total_Stops.replace({'non-stop':0,'2 stops':2 ,'1 stop': 1,'3 stops':3,'4 stops':4})

C:\Users\ACER\AppData\Local\Temp\ipykernel_17476\4202769285.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.Total_Stops = df.Total_Stops.replace({'non-stop':0,'2 stops':2 ,'1 stop': 1,'3 stops':3,'4 stops':4})

In [34]:
df

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Day,Month,Year,Arriva_Hour,Arriva_Minute,Dep_Hour,Dep_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2,No info,7662,1,5,2019,13,15,05,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2,No info,13882,9,6,2019,4,25,09,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1,No info,6218,12,5,2019,23,30,18,05
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1,No info,13302,1,3,2019,21,35,16,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,2h 30m,0,No info,4107,9,4,2019,22,25,19,55
10679,Air India,Kolkata,Banglore,CCU → BLR,2h 35m,0,No info,4145,27,4,2019,23,20,20,45
10680,Jet Airways,Banglore,Delhi,BLR → DEL,3h,0,No info,7229,27,4,2019,11,20,08,20
10681,Vistara,Banglore,New Delhi,BLR → DEL,2h 40m,0,No info,12648,1,3,2019,14,10,11,30
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,8h 20m,2,No info,11753,9,5,2019,19,15,10,55

In [35]:
df.Total_Stops.astype(int)

0        0
1        2
2        2
3        1
4        1
        ..
10678    0
10679    0
10680    0
10681    0
10682    2
Name: Total_Stops, Length: 10682, dtype: int64

In [36]:
df['Duration_Hour'] = df.Duration.str.split(' ').str[0]
df['Duration_Hour']

0         2h
1         7h
2        19h
3         5h
4         4h
        ...
10678     2h
10679     2h
10680     3h
10681     2h
10682     8h
Name: Duration_Hour, Length: 10682, dtype: object

In [37]:
df['Duration_Hour'] = df['Duration_Hour'].str.replace('h', '')
df['Duration_Hour'] = df['Duration_Hour'].str.replace('m', '')

In [38]:
df['Duration_Min'] = df.Duration.str.split(' ').str[1]
df['Duration_Min']

0        50m
1        25m
2        NaN
3        25m
4        45m
        ...
10678    30m
10679    35m
10680    NaN
10681    40m
10682    20m
Name: Duration_Min, Length: 10682, dtype: object

In [39]:

df['Duration_Min'] = df['Duration_Min'].str.replace('m',' ')
df['Duration_Min'] = df['Duration_Min'].fillna('0')


df['Duration_Min']

0        50
1        25
2          0
3        25
4        45
        ...
10678    30
10679    35
10680      0
10681    40
10682    20
Name: Duration_Min, Length: 10682, dtype: object

In [40]:
df.drop('Duration', inplace = True, axis = 1)

In [41]:
df.sample(2)

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,Day,Month,Year,Arriva_Hour,Arriva_Minute,Dep_Hour,Dep_Minute,Duration_Hour,Duration_Min
8724,Air India,Delhi,Cochin,DEL → HYD → MAA → COK,2,No info,10467,3,6,2019,9,25,13,15,20,10
8994,IndiGo,Kolkata,Banglore,CCU → BLR,0,No info,4804,3,6,2019,14,5,11,30,2,35

In [42]:
df.isnull().sum()

Airline            0
Source             0
Destination        0
Route              0
Total_Stops        0
Additional_Info    0
Price              0
Day                0
Month              0
Year               0
Arriva_Hour        0
Arriva_Minute      0
Dep_Hour           0
Dep_Minute         0
Duration_Hour      0
Duration_Min       0
dtype: int64

In [43]:
df['Duration_Hour'] = df['Duration_Hour'].astype(int)
df['Duration_Min'] = df['Duration_Min'].astype(int)

In [44]:
df['Duration_Min'].unique()

array([50, 25,  0, 45, 30,  5, 15, 35, 10, 20, 55, 40])

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Total_Stops      10682 non-null  int64
 5   Additional_Info  10682 non-null  object
 6   Price            10682 non-null  int64
 7   Day              10682 non-null  int64
 8   Month            10682 non-null  int64
 9   Year             10682 non-null  int64
 10  Arriva_Hour      10682 non-null  int64
 11  Arriva_Minute    10682 non-null  int64
 12  Dep_Hour         10682 non-null  object
 13  Dep_Minute       10682 non-null  object
 14  Duration_Hour    10682 non-null  int64
 15  Duration_Min     10682 non-null  int64
dtypes: int64(9), object(7)
memory usage: 1.4+ MB

In [46]:
df['Dep_Hour'] = df['Dep_Hour'].astype(int)
df['Dep_Minute'] = df['Dep_Minute'].astype(int)

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Total_Stops      10682 non-null  int64
 5   Additional_Info  10682 non-null  object
 6   Price            10682 non-null  int64
 7   Day              10682 non-null  int64
 8   Month            10682 non-null  int64
 9   Year             10682 non-null  int64
 10  Arriva_Hour      10682 non-null  int64
 11  Arriva_Minute    10682 non-null  int64
 12  Dep_Hour         10682 non-null  int64
 13  Dep_Minute       10682 non-null  int64
 14  Duration_Hour    10682 non-null  int64
 15  Duration_Min     10682 non-null  int64
dtypes: int64(11), object(5)
memory usage: 1.4+ MB

In [48]:
cat_col = df.select_dtypes(exclude = 'number').columns

In [49]:
num_col =  df.select_dtypes(include = 'number').columns

In [50]:
df[cat_col]

,Airline,Source,Destination,Route,Additional_Info
0,IndiGo,Banglore,New Delhi,BLR → DEL,No info
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,No info
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,No info
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,No info
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,No info
...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,No info
10679,Air India,Kolkata,Banglore,CCU → BLR,No info
10680,Jet Airways,Banglore,Delhi,BLR → DEL,No info
10681,Vistara,Banglore,New Delhi,BLR → DEL,No info
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,No info

In [51]:
from sklearn.preprocessing import OneHotEncoder

encode = OneHotEncoder()

In [52]:
encoded_data = encode.fit_transform(df[cat_col]).toarray()

In [53]:
encode.get_feature_names_out()

array(['Airline_Air Asia', 'Airline_Air India', 'Airline_GoAir',
       'Airline_IndiGo', 'Airline_Jet Airways',
       'Airline_Jet Airways Business', 'Airline_Multiple carriers',
       'Airline_Multiple carriers Premium economy', 'Airline_SpiceJet',
       'Airline_Trujet', 'Airline_Vistara',
       'Airline_Vistara Premium economy', 'Source_Banglore',
       'Source_Chennai', 'Source_Delhi', 'Source_Kolkata',
       'Source_Mumbai', 'Destination_Banglore', 'Destination_Cochin',
       'Destination_Delhi', 'Destination_Hyderabad',
       'Destination_Kolkata', 'Destination_New Delhi',
       'Route_BLR → AMD → DEL', 'Route_BLR → BBI → DEL',
       'Route_BLR → BDQ → DEL', 'Route_BLR → BOM → AMD → DEL',
       'Route_BLR → BOM → BHO → DEL', 'Route_BLR → BOM → DEL',
       'Route_BLR → BOM → IDR → DEL', 'Route_BLR → BOM → IDR → GWL → DEL',
       'Route_BLR → BOM → IXC → DEL', 'Route_BLR → BOM → JDH → DEL',
       'Route_BLR → BOM → NAG → DEL', 'Route_BLR → BOM → UDR → DEL',
       'Route_BLR → CCU → BBI → DEL', 'Route_BLR → CCU → BBI → HYD → DEL',
       'Route_BLR → CCU → BBI → HYD → VGA → DEL', 'Route_BLR → CCU → DEL',
       'Route_BLR → CCU → GAU → DEL', 'Route_BLR → COK → DEL',
       'Route_BLR → DEL', 'Route_BLR → GAU → DEL',
       'Route_BLR → GOI → DEL', 'Route_BLR → HBX → BOM → AMD → DEL',
       'Route_BLR → HBX → BOM → BHO → DEL',
       'Route_BLR → HBX → BOM → NAG → DEL', 'Route_BLR → HYD → DEL',
       'Route_BLR → HYD → VGA → DEL', 'Route_BLR → IDR → DEL',
       'Route_BLR → LKO → DEL', 'Route_BLR → MAA → DEL',
       'Route_BLR → NAG → DEL', 'Route_BLR → PNQ → DEL',
       'Route_BLR → STV → DEL', 'Route_BLR → TRV → COK → DEL',
       'Route_BLR → VGA → DEL', 'Route_BLR → VGA → HYD → DEL',
       'Route_BLR → VGA → VTZ → DEL', 'Route_BOM → AMD → ISK → HYD',
       'Route_BOM → BBI → HYD', 'Route_BOM → BDQ → DEL → HYD',
       'Route_BOM → BHO → DEL → HYD', 'Route_BOM → BLR → CCU → BBI → HYD',
       'Route_BOM → BLR → HYD', 'Route_BOM → CCU → HYD',
       'Route_BOM → COK → MAA → HYD', 'Route_BOM → DED → DEL → HYD',
       'Route_BOM → DEL → HYD', 'Route_BOM → GOI → HYD',
       'Route_BOM → GOI → PNQ → HYD', 'Route_BOM → HYD',
       'Route_BOM → IDR → DEL → HYD', 'Route_BOM → JAI → DEL → HYD',
       'Route_BOM → JDH → DEL → HYD', 'Route_BOM → JDH → JAI → DEL → HYD',
       'Route_BOM → JLR → HYD', 'Route_BOM → MAA → HYD',
       'Route_BOM → NDC → HYD', 'Route_BOM → RPR → VTZ → HYD',
       'Route_BOM → UDR → DEL → HYD', 'Route_BOM → VNS → DEL → HYD',
       'Route_CCU → AMD → BLR', 'Route_CCU → BBI → BLR',
       'Route_CCU → BBI → BOM → BLR', 'Route_CCU → BBI → HYD → BLR',
       'Route_CCU → BBI → IXR → DEL → BLR', 'Route_CCU → BLR',
       'Route_CCU → BOM → AMD → BLR', 'Route_CCU → BOM → BLR',
       'Route_CCU → BOM → COK → BLR', 'Route_CCU → BOM → GOI → BLR',
       'Route_CCU → BOM → HBX → BLR', 'Route_CCU → BOM → PNQ → BLR',
       'Route_CCU → BOM → TRV → BLR', 'Route_CCU → DEL → AMD → BLR',
       'Route_CCU → DEL → BLR', 'Route_CCU → DEL → COK → BLR',
       'Route_CCU → DEL → COK → TRV → BLR', 'Route_CCU → DEL → VGA → BLR',
       'Route_CCU → GAU → BLR', 'Route_CCU → GAU → DEL → BLR',
       'Route_CCU → GAU → IMF → DEL → BLR', 'Route_CCU → HYD → BLR',
       'Route_CCU → IXA → BLR', 'Route_CCU → IXB → BLR',
       'Route_CCU → IXB → DEL → BLR', 'Route_CCU → IXR → BBI → BLR',
       'Route_CCU → IXR → DEL → BLR', 'Route_CCU → IXZ → MAA → BLR',
       'Route_CCU → JAI → BOM → BLR', 'Route_CCU → JAI → DEL → BLR',
       'Route_CCU → KNU → BLR', 'Route_CCU → MAA → BLR',
       'Route_CCU → NAG → BLR', 'Route_CCU → PAT → BLR',
       'Route_CCU → PNQ → BLR', 'Route_CCU → RPR → HYD → BLR',
       'Route_CCU → VNS → DEL → BLR', 'Route_CCU → VTZ → BLR',
       'Route_DEL → AMD → BOM → COK', 'Route_DEL → AMD → COK',
       'Route_DEL → ATQ → BOM → COK', 'Route_DEL → BBI → COK',
       'Route_DEL → BDQ → BOM → COK', 'Route_DEL → BHO → BOM → COK',
       'Route_DEL → BLR → COK', 'Route_DEL → BOM → COK',
       'Route_DEL → CCU → BOM → COK', 'Route_DEL → COK',
       'Route_DEL → DED → BOM → COK', 'Route_DEL → GOI → BOM → COK',
       'Route_DEL → GWL → IDR → BOM → COK', 'Route_DEL → HYD → BOM → COK',
       'Route_DEL → HYD → COK', 'Route_DEL → HYD → MAA → COK',
       'Route_DEL → IDR → BOM → COK', 'Route_DEL → IXC → BOM → COK',
       'Route_DEL → IXU → BOM → COK', 'Route_DEL → JAI → BOM → COK',
       'Route_DEL → JDH → BOM → COK', 'Route_DEL → LKO → BOM → COK',
       'Route_DEL → LKO → COK', 'Route_DEL → MAA → BOM → COK',
       'Route_DEL → MAA → COK', 'Route_DEL → NAG → BOM → COK',
       'Route_DEL → PNQ → COK', 'Route_DEL → RPR → NAG → BOM → COK',
       'Route_DEL → TRV → COK', 'Route_DEL → UDR → BOM → COK',
       'Route_MAA → CCU', 'Additional_Info_1 Long layover',
       'Additional_Info_1 Short layover',
       'Additional_Info_2 Long layover', 'Additional_Info_Business class',
       'Additional_Info_Change airports',
       'Additional_Info_In-flight meal not included',
       'Additional_Info_No Info',
       'Additional_Info_No check-in baggage included',
       'Additional_Info_No info', 'Additional_Info_Red-eye flight'],
      dtype=object)

In [54]:
encoded_df = pd.DataFrame(encoded_data, columns= encode.get_feature_names_out())

In [55]:
df.drop(cat_col, axis = 1, inplace = True)

In [56]:
df

,Total_Stops,Price,Day,Month,Year,Arriva_Hour,Arriva_Minute,Dep_Hour,Dep_Minute,Duration_Hour,Duration_Min
0,0,3897,24,3,2019,1,10,22,20,2,50
1,2,7662,1,5,2019,13,15,5,50,7,25
2,2,13882,9,6,2019,4,25,9,25,19,0
3,1,6218,12,5,2019,23,30,18,5,5,25
4,1,13302,1,3,2019,21,35,16,50,4,45
...,...,...,...,...,...,...,...,...,...,...,...
10678,0,4107,9,4,2019,22,25,19,55,2,30
10679,0,4145,27,4,2019,23,20,20,45,2,35
10680,0,7229,27,4,2019,11,20,8,20,3,0
10681,0,12648,1,3,2019,14,10,11,30,2,40
10682,2,11753,9,5,2019,19,15,10,55,8,20

In [57]:
final_df = pd.concat([df,encoded_df],axis = 1)

In [58]:
final_df

,Total_Stops,Price,Day,Month,Year,Arriva_Hour,Arriva_Minute,Dep_Hour,Dep_Minute,Duration_Hour,...,Additional_Info_1 Long layover,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
0,0.0,3897.0,24.0,3.0,2019.0,1.0,10.0,22.0,20.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,2.0,7662.0,1.0,5.0,2019.0,13.0,15.0,5.0,50.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,2.0,13882.0,9.0,6.0,2019.0,4.0,25.0,9.0,25.0,19.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1.0,6218.0,12.0,5.0,2019.0,23.0,30.0,18.0,5.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1.0,13302.0,1.0,3.0,2019.0,21.0,35.0,16.0,50.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10679,0.0,4145.0,27.0,4.0,2019.0,23.0,20.0,20.0,45.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10680,0.0,7229.0,27.0,4.0,2019.0,11.0,20.0,8.0,20.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10681,0.0,12648.0,1.0,3.0,2019.0,14.0,10.0,11.0,30.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10682,2.0,11753.0,9.0,5.0,2019.0,19.0,15.0,10.0,55.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9039,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [59]:
print(final_df.dtypes)

Total_Stops                                     float64
Price                                           float64
Day                                             float64
Month                                           float64
Year                                            float64
                                                 ...
Additional_Info_In-flight meal not included     float64
Additional_Info_No Info                         float64
Additional_Info_No check-in baggage included    float64
Additional_Info_No info                         float64
Additional_Info_Red-eye flight                  float64
Length: 172, dtype: object